"""Dedicated local-potential and electric-field workflows."""

from .potential_and_electric_field_workflow import (
    ALL_LEGACY_COMMANDS as ANALYSIS_LEGACY_COMMANDS,
    COMMAND as ANALYSIS_COMMAND,
)
from .trajectory_workflow import (
    ALL_LEGACY_COMMANDS as TRAJECTORY_LEGACY_COMMANDS,
    COMMAND as TRAJECTORY_COMMAND,
)

ALL_COMMANDS = (ANALYSIS_COMMAND, TRAJECTORY_COMMAND)
ALL_LEGACY_COMMANDS = (*ANALYSIS_LEGACY_COMMANDS, *TRAJECTORY_LEGACY_COMMANDS)

__all__ = ["ALL_COMMANDS", "ALL_LEGACY_COMMANDS", "ANALYSIS_COMMAND", "TRAJECTORY_COMMAND"]
