"""Config-driven active-control step example for ROMP workflows.

Pipeline:
1) Read fort.90 coordinates/connectivity with GeoHandler
2) Identify molecules by connected components and remove target formulas
3) Add monomer near random anchor (with overlap checks)
4) Write next-step GEO using xtob (existing ReaxKit writer path)
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

import numpy as np
import pandas as pd
import yaml


def _ensure_reaxkit_importable() -> None:
    try:
        import reaxkit  # noqa: F401
        return
    except Exception:
        pass

    script_dir = Path(__file__).resolve().parent
    for candidate in (script_dir, *script_dir.parents):
        src_dir = candidate / "src"
        if (src_dir / "reaxkit").exists():
            sys.path.insert(0, str(src_dir))
            return


_ensure_reaxkit_importable()

from reaxkit.engine.reaxff.io.geo_handler import GeoHandler

from romp_edit_ops import (
    analyze_molecules_with_components,
    append_monomer_at_point,
    choose_anchor_and_nearest,
    connectivity_groups_from_detection,
    find_nonoverlapping_point,
    formula_count_table,
    molecules_from_detection_result,
    monomer_relative_to_com,
    remove_atoms_by_id,
    select_atoms_to_remove_by_formula,
    select_atoms_to_remove_by_rules,
)


def _get_nested(cfg: dict[str, Any], *keys: str, default=None):
    cur: Any = cfg
    for key in keys:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    return cur


def _resolve_path(base_dir: Path, value: str | None) -> Path | None:
    if value is None:
        return None
    p = Path(str(value))
    if p.is_absolute():
        return p
    return (base_dir / p).resolve()


def _format_crystx(box_lengths: list[float], box_angles: list[float]) -> str:
    values = (*box_lengths, *box_angles)
    return "CRYSTX" + "".join(f"{value:11.5f}" for value in values)


def _format_hetatm_line(atom_id: int, atom_type: str, x: float, y: float, z: float) -> str:
    at2 = atom_type.strip()[:2]
    at5 = atom_type.strip()[:5]
    return (
        "HETATM"
        f" {atom_id:5d}"
        f" {at2:2s}"
        "   "
        " "
        "   "
        " "
        " "
        " "
        "     "
        f"{x:10.5f}{y:10.5f}{z:10.5f}"
        f" {at5:5s}"
        f"{0:3d}{0:2d}"
        f" {0.0:8.5f}"
    )


def _write_geo(
    path: Path,
    coordinates: pd.DataFrame,
    *,
    box_lengths: list[float],
    box_angles: list[float],
    descriptor: str = "active_control_step",
) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    coords = coordinates.sort_values("atom_id", kind="stable").reset_index(drop=True)
    lines = [
        "XTLGRF 200",
        f"DESCRP  {descriptor}",
        "REMARK generated by ROMP active-control example",
        _format_crystx(box_lengths, box_angles),
        "FORMAT ATOM   (a6,1x,i5,1x,a5,1x,a3,1x,a1,1x,a5,3f10.5,1x,a5,i3,i2,1x,f8.5)",
    ]
    for new_atom_id, row in enumerate(coords.itertuples(index=False), start=1):
        lines.append(
            _format_hetatm_line(
                new_atom_id,
                str(row.atom_type),
                float(row.x),
                float(row.y),
                float(row.z),
            )
        )
    lines.append("END")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _filter_connectivity_by_atom_ids(connectivity: pd.DataFrame, atom_ids: set[int]) -> pd.DataFrame:
    if connectivity.empty:
        return pd.DataFrame(columns=["source_atom_id", "target_atom_id"])
    filtered = connectivity[
        connectivity["source_atom_id"].astype(int).isin(atom_ids)
        & connectivity["target_atom_id"].astype(int).isin(atom_ids)
    ].copy()
    return filtered.reset_index(drop=True)


def _write_text_report(path: Path, report: dict[str, Any]) -> Path:
    lines = [
        f"input_fort90: {report.get('input_fort90')}",
        f"input_monomer: {report.get('input_monomer')}",
        f"output_geo: {report.get('output_geo')}",
        f"seed: {report.get('seed')}",
        f"before_atom_count: {report.get('before_atom_count')}",
        f"removed_atom_count: {report.get('removed_atom_count')}",
        f"inserted_atom_count: {report.get('inserted_atom_count')}",
        f"after_atom_count: {report.get('after_atom_count')}",
        f"removal_mode: {report.get('removal_mode')}",
        f"removal_selection_strategy: {report.get('removal_selection_strategy')}",
        f"insertion_status: {report.get('insertion_status')}",
        f"insertion_min_distance_threshold: {report.get('insertion_min_distance_threshold')}",
        f"insertion_min_distance_observed: {report.get('insertion_min_distance_observed')}",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _load_coordinates(path: Path) -> pd.DataFrame:
    handler = GeoHandler(path)
    coords = handler.coordinates().copy()
    required = {"atom_id", "atom_type", "x", "y", "z"}
    missing = required.difference(set(coords.columns))
    if missing:
        raise ValueError(f"{path} missing required coordinate columns: {sorted(missing)}")
    coords = coords.loc[:, ["atom_id", "atom_type", "x", "y", "z"]].copy()
    coords["atom_id"] = pd.to_numeric(coords["atom_id"], errors="coerce").astype(int)
    coords["atom_type"] = coords["atom_type"].astype(str)
    coords["x"] = pd.to_numeric(coords["x"], errors="coerce")
    coords["y"] = pd.to_numeric(coords["y"], errors="coerce")
    coords["z"] = pd.to_numeric(coords["z"], errors="coerce")
    return coords


def _load_connectivity(path: Path) -> pd.DataFrame:
    handler = GeoHandler(path)
    conn = handler.connectivity().copy()
    if conn.empty:
        return pd.DataFrame(columns=["source_atom_id", "target_atom_id"])
    required = {"source_atom_id", "target_atom_id"}
    missing = required.difference(set(conn.columns))
    if missing:
        raise ValueError(f"{path} missing required connectivity columns: {sorted(missing)}")
    conn = conn.loc[:, ["source_atom_id", "target_atom_id"]].copy()
    conn["source_atom_id"] = pd.to_numeric(conn["source_atom_id"], errors="coerce").astype(int)
    conn["target_atom_id"] = pd.to_numeric(conn["target_atom_id"], errors="coerce").astype(int)
    return conn


def _main_impl(config_path: Path) -> int:
    cfg = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    base_dir = config_path.parent

    fort90 = _resolve_path(base_dir, _get_nested(cfg, "input", "fort90"))
    monomer = _resolve_path(base_dir, _get_nested(cfg, "input", "monomer"))
    if fort90 is None or not fort90.exists():
        raise FileNotFoundError(f"fort90 path not found: {fort90}")
    if monomer is None or not monomer.exists():
        raise FileNotFoundError(f"monomer path not found: {monomer}")

    geo_out = _resolve_path(base_dir, _get_nested(cfg, "output", "geo_out", default="geo_next"))
    report_out = _resolve_path(base_dir, _get_nested(cfg, "output", "report_json", default="active_step_report.json"))
    report_txt_out = _resolve_path(base_dir, _get_nested(cfg, "output", "report_txt", default="active_step_report.txt"))
    rng_seed = int(_get_nested(cfg, "insertion", "seed", default=42))
    rng = np.random.default_rng(rng_seed)

    coordinates = _load_coordinates(fort90)
    connectivity = _load_connectivity(fort90)
    monomer_coords = _load_coordinates(monomer)

    before_atom_count = int(len(coordinates))
    detection_before = analyze_molecules_with_components(coordinates, connectivity)
    molecules_before = molecules_from_detection_result(detection_before, coordinates)
    formula_before = formula_count_table(detection_before)
    groups_before = connectivity_groups_from_detection(detection_before)

    removed_atom_ids: set[int] = set()
    removed_molecule_formulas: list[str] = []
    removed_molecule_ids: list[int] = []
    removal_mode = str(_get_nested(cfg, "removal", "mode", default="formula")).strip().lower()
    removal_strategy = str(_get_nested(cfg, "removal", "selection_strategy", default="first")).strip().lower()
    if bool(_get_nested(cfg, "removal", "enabled", default=True)):
        max_remove = _get_nested(cfg, "removal", "max_molecules", default=None)
        if removal_mode == "rules":
            rules = _get_nested(cfg, "removal", "rules", default={}) or {}
            if not isinstance(rules, dict):
                raise ValueError("removal.rules must be a mapping when removal.mode is 'rules'.")
            removed_atom_ids, removed_molecules = select_atoms_to_remove_by_rules(
                molecules_before,
                include_any_elements=rules.get("include_any_elements"),
                include_all_elements=rules.get("include_all_elements"),
                exclude_any_elements=rules.get("exclude_any_elements"),
                allowed_elements=rules.get("allowed_elements"),
                include_motifs=rules.get("include_motifs"),
                exclude_motifs=rules.get("exclude_motifs"),
                max_molecules=max_remove,
                selection_strategy=removal_strategy,
                rng=rng,
            )
        else:
            target_formulas = _get_nested(cfg, "removal", "target_formulas", default=["C8H12"])
            removed_atom_ids, removed_molecules = select_atoms_to_remove_by_formula(
                molecules_before,
                target_formulas=target_formulas,
                max_molecules=max_remove,
                selection_strategy=removal_strategy,
                rng=rng,
            )
        removed_molecule_formulas = [m.formula for m in removed_molecules]
        removed_molecule_ids = [int(m.molecule_id) for m in removed_molecules]
        coordinates = remove_atoms_by_id(coordinates, removed_atom_ids)

    inserted_atoms = 0
    insertion_status = "skipped"
    inserted_min_distance_observed: float | None = None
    place_count = int(_get_nested(cfg, "insertion", "place_count", default=1))
    if bool(_get_nested(cfg, "insertion", "enabled", default=True)) and place_count > 0:
        monomer_symbols, monomer_rel = monomer_relative_to_com(monomer_coords)
        anchor_element = str(_get_nested(cfg, "insertion", "anchor_element", default="Ru"))
        nearest_element = str(_get_nested(cfg, "insertion", "nearest_element", default="C"))
        radius = float(_get_nested(cfg, "insertion", "search_radius", default=7.5))
        min_distance = float(_get_nested(cfg, "insertion", "min_distance", default=3.0))
        samples = int(_get_nested(cfg, "insertion", "candidate_samples", default=10000))

        inserted_success = 0
        for _ in range(place_count):
            anchor, _nearest = choose_anchor_and_nearest(
                coordinates,
                anchor_element=anchor_element,
                nearest_element=nearest_element,
                rng=rng,
            )
            anchor_xyz = np.asarray([float(anchor["x"]), float(anchor["y"]), float(anchor["z"])], dtype=float)
            existing_xyz = coordinates[["x", "y", "z"]].to_numpy(dtype=float)
            point = find_nonoverlapping_point(
                existing_xyz,
                monomer_rel,
                anchor_xyz,
                radius=radius,
                min_distance=min_distance,
                n_samples=samples,
                rng=rng,
            )
            if point is None:
                continue
            placed_xyz = monomer_rel + point
            if existing_xyz.size > 0 and placed_xyz.size > 0:
                pairwise = np.linalg.norm(existing_xyz[None, :, :] - placed_xyz[:, None, :], axis=2)
                this_min = float(pairwise.min())
                if inserted_min_distance_observed is None or this_min < inserted_min_distance_observed:
                    inserted_min_distance_observed = this_min
            coordinates = append_monomer_at_point(coordinates, monomer_symbols, monomer_rel, point)
            inserted_success += 1

        inserted_atoms = inserted_success * int(len(monomer_symbols))
        insertion_status = "ok" if inserted_success == place_count else "partial_or_failed"

    # Determine output box settings from config or input metadata.
    in_meta = GeoHandler(fort90).metadata()
    cell_lengths = in_meta.get("cell_lengths") or {}
    cell_angles = in_meta.get("cell_angles") or {}
    box_lengths = _get_nested(
        cfg,
        "box",
        "lengths",
        default=[cell_lengths.get("a", 100.0), cell_lengths.get("b", 100.0), cell_lengths.get("c", 100.0)],
    )
    box_angles = _get_nested(
        cfg,
        "box",
        "angles",
        default=[cell_angles.get("alpha", 90.0), cell_angles.get("beta", 90.0), cell_angles.get("gamma", 90.0)],
    )
    box_lengths = [float(x) for x in box_lengths]
    box_angles = [float(x) for x in box_angles]

    _write_geo(
        geo_out,
        coordinates,
        box_lengths=box_lengths,
        box_angles=box_angles,
    )

    after_atom_count = int(len(coordinates))
    atom_ids_after = set(int(v) for v in coordinates["atom_id"].astype(int).tolist())
    connectivity_after = _filter_connectivity_by_atom_ids(connectivity, atom_ids_after)
    detection_after = analyze_molecules_with_components(coordinates, connectivity_after)
    formula_after = formula_count_table(detection_after)
    groups_after = connectivity_groups_from_detection(detection_after)
    insertion_min_distance = float(_get_nested(cfg, "insertion", "min_distance", default=3.0))
    report = {
        "input_fort90": str(fort90),
        "input_monomer": str(monomer),
        "output_geo": str(geo_out),
        "seed": rng_seed,
        "before_atom_count": before_atom_count,
        "after_atom_count": after_atom_count,
        "removal_mode": removal_mode,
        "removal_selection_strategy": removal_strategy,
        "removed_atom_count": int(len(removed_atom_ids)),
        "removed_molecule_ids": removed_molecule_ids,
        "removed_molecule_formulas": removed_molecule_formulas,
        "inserted_atom_count": inserted_atoms,
        "insertion_status": insertion_status,
        "insertion_min_distance_threshold": insertion_min_distance,
        "insertion_min_distance_observed": inserted_min_distance_observed,
        "molecule_component_count_before": int(len(groups_before)),
        "molecule_component_count_after": int(len(groups_after)),
        "formula_counts_before": formula_before.to_dict(orient="records"),
        "formula_counts_after": formula_after.to_dict(orient="records"),
        "box_lengths": box_lengths,
        "box_angles": box_angles,
    }
    report_out.parent.mkdir(parents=True, exist_ok=True)
    report_out.write_text(json.dumps(report, indent=2), encoding="utf-8")
    if report_txt_out is not None:
        _write_text_report(report_txt_out, report)

    print(f"Wrote next-step GEO: {geo_out}")
    print(f"Wrote report: {report_out}")
    if report_txt_out is not None:
        print(f"Wrote report: {report_txt_out}")
    print(
        f"Atoms: before={before_atom_count} removed={len(removed_atom_ids)} "
        f"inserted={inserted_atoms} after={after_atom_count}"
    )
    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="ROMP active-control example step runner.")
    parser.add_argument(
        "--config",
        default=str(Path(__file__).resolve().parent / "config.yaml"),
        help="Path to YAML configuration file.",
    )
    return parser


def main() -> int:
    args = _build_parser().parse_args()
    return _main_impl(Path(args.config).resolve())


if __name__ == "__main__":
    raise SystemExit(main())
