name: "Feature request"
description: "Suggest a new feature for reaxkit"
labels: ["enhancement"]

body:
  - type: dropdown
    id: module
    attributes:
      label: Related to which ReaxFF file(s)?
      options:
        - fort7
        - xmolout
        - summary
        - else
    validations:
      required: true

  - type: input
    id: file
    attributes:
      label: Main file affected
      placeholder: src/reaxkit/...

  - type: textarea
    id: description
    attributes:
      label: Feature description
      placeholder: Explain the feature...
    validations:
      required: true
