"""Reviewed canonical flag roles for the registered CLI."""

FLAG_METADATA = {
    # Legacy spellings and branch-specific flags also appear in generated docs.
    '--anion': ('Scientific choices', 'full'),
    '--bo': ('Scientific choices', 'full'),
    '--cation': ('Scientific choices', 'full'),
    '--closest': ('Scientific choices', 'full'),
    '--dest': ('Outputs and plots', 'full'),
    '--dir': ('Input and file selection', 'full'),
    '--each-range': ('Scientific choices', 'full'),
    '--each-type': ('Scientific choices', 'full'),
    '--mp-id': ('Input and file selection', 'full'),
    '--n-extreme-atoms': ('Scientific choices', 'full'),
    '--no-global-scaling': ('Outputs and plots', 'full'),
    '--no-include-noncarbon': ('Scientific choices', 'full'),
    '--no-orthogonalize-reference': ('Scientific choices', 'full'),
    '--no-undirected': ('Scientific choices', 'full'),
    '--no-unwrap': ('Scientific choices', 'full'),
    '--per-type': ('Scientific choices', 'full'),
    '--plot-evolution': ('Outputs and plots', 'full'),
    '--stride': ('Scientific choices', 'full'),
    '--together-charge': ('Scientific choices', 'full'),
    '--wait': ('Execution', 'full'),
    '--action': ('Scientific choices', 'full'),
    '--agg': ('Scientific choices', 'full'),
    '--aggregate': ('Scientific choices', 'full'),
    '--aggregate-title': ('Outputs and plots', 'full'),
    '--all-info': ('Outputs and plots', 'full'),
    '--allow-missing-valences': ('Scientific choices', 'full'),
    '--allow-undefined-hybridization': ('Scientific choices', 'full'),
    '--alpha': ('Scientific choices', 'full'),
    '--alpha-radius': ('Scientific choices', 'full'),
    '--amplitude': ('Scientific choices', 'full'),
    '--analysis': ('Storage and cache', 'full'),
    '--analysis-id': ('Storage and cache', 'full'),
    '--analysis-title': ('Outputs and plots', 'full'),
    '--analyze': ('Scientific choices', 'full'),
    '--angle': ('Scientific choices', 'full'),
    '--angles': ('Scientific choices', 'short'),
    '--angle-tolerance': ('Scientific choices', 'full'),
    '--any-order': ('Scientific choices', 'full'),
    '--api-key': ('Diagnostics and compatibility', 'short'),
    '--artifact-transfer': ('Storage and cache', 'full'),
    '--atom': ('Scientific choices', 'short'),
    '--atom-ids': ('Scientific choices', 'short'),
    '--atom-ids-a': ('Scientific choices', 'short'),
    '--atom-ids-b': ('Scientific choices', 'short'),
    '--atom-numbers': ('Scientific choices', 'short'),
    '--atoms': ('Scientific choices', 'short'),
    '--atom-types': ('Scientific choices', 'short'),
    '--atom-types-a': ('Scientific choices', 'full'),
    '--atom-types-b': ('Scientific choices', 'full'),
    '--average': ('Scientific choices', 'full'),
    '--azim': ('Outputs and plots', 'full'),
    '--backend': ('Execution', 'full'),
    '--base': ('Input and file selection', 'full'),
    '--baseline': ('Scientific choices', 'full'),
    '--baseplace': ('Scientific choices', 'full'),
    '--bin-axes': ('Scientific choices', 'full'),
    '--bin-range': ('Scientific choices', 'full'),
    '--bins': ('Scientific choices', 'short'),
    '--bins-x': ('Scientific choices', 'full'),
    '--bins-y': ('Scientific choices', 'full'),
    '--bins-z': ('Scientific choices', 'full'),
    '--bond': ('Scientific choices', 'short'),
    '--bond-mode': ('Scientific choices', 'full'),
    '--bond-scale': ('Scientific choices', 'full'),
    '--bo-threshold': ('Scientific choices', 'short'),
    '--bounds': ('Scientific choices', 'full'),
    '--boxdims': ('Scientific choices', 'full'),
    '--bulk-mode': ('Scientific choices', 'full'),
    '--carbon-element': ('Scientific choices', 'full'),
    '--case': ('Storage and cache', 'full'),
    '--c-axis': ('Scientific choices', 'full'),
    '--cell-angles': ('Scientific choices', 'full'),
    '--cell-fields': ('Scientific choices', 'full'),
    '--cell-lengths': ('Scientific choices', 'full'),
    '--center': ('Scientific choices', 'full'),
    '--centers-format': ('Outputs and plots', 'full'),
    '--charge-source': ('Scientific choices', 'short'),
    '--chunk-size': ('Execution', 'full'),
    '--clip-fraction': ('Scientific choices', 'full'),
    '--closest-atom': ('Scientific choices', 'full'),
    '--closest-term': ('Scientific choices', 'full'),
    '--cmap': ('Outputs and plots', 'full'),
    '--col': ('Outputs and plots', 'full'),
    '--color-scale': ('Outputs and plots', 'full'),
    '--complete-only': ('Scientific choices', 'full'),
    '--component': ('Scientific choices', 'short'),
    '--components': ('Scientific choices', 'short'),
    '--composition-file': ('Input and file selection', 'full'),
    '--compress': ('Outputs and plots', 'full'),
    '--control': ('Input and file selection', 'short'),
    '--copy-to-dot': ('Outputs and plots', 'full'),
    '--core': ('Scientific choices', 'short'),
    '--crystallographic-setting-conversion': ('Scientific choices', 'full'),
    '--d': ('Scientific choices', 'full'),
    '--data-kind': ('Scientific choices', 'short'),
    '--dc-offset': ('Scientific choices', 'full'),
    '--default': ('Scientific choices', 'full'),
    '--deformation-neighbors': ('Scientific choices', 'full'),
    '--delta-t-ps': ('Scientific choices', 'full'),
    '--descending': ('Scientific choices', 'full'),
    '--destination': ('Outputs and plots', 'short'),
    '--detail-format': ('Outputs and plots', 'full'),
    '--diagnose': ('Diagnostics and compatibility', 'full'),
    '--diagram-dim': ('Outputs and plots', 'full'),
    '--dims': ('Scientific choices', 'full'),
    '--dipole-column': ('Scientific choices', 'full'),
    '--dipole-kind': ('Scientific choices', 'full'),
    '--dipole-unit': ('Scientific choices', 'short'),
    '--dipole-zero-tolerance': ('Scientific choices', 'full'),
    '--directed': ('Scientific choices', 'full'),
    '--direction': ('Scientific choices', 'short'),
    '--disable-taper': ('Scientific choices', 'full'),
    '--disallow-torsion-wildcard': ('Scientific choices', 'full'),
    '--dpi': ('Outputs and plots', 'full'),
    '--dropna-rows': ('Scientific choices', 'full'),
    '--dry-run': ('Execution', 'full'),
    '--dst': ('Scientific choices', 'full'),
    '--dt': ('Scientific choices', 'full'),
    '--dump': ('Outputs and plots', 'full'),
    '--element': ('Scientific choices', 'short'),
    '--element-count-scope': ('Scientific choices', 'full'),
    '--element-hybridizations': ('Scientific choices', 'full'),
    '--elements': ('Scientific choices', 'short'),
    '--elev': ('Outputs and plots', 'full'),
    '--ema-alpha': ('Scientific choices', 'full'),
    '--energylog': ('Input and file selection', 'full'),
    '--engine': ('Input and file selection', 'short'),
    '--entry-per-figure': ('Outputs and plots', 'full'),
    '--epochs': ('Scientific choices', 'full'),
    '--eregime': ('Input and file selection', 'full'),
    '--every': ('Scientific choices', 'short'),
    '--exact-match': ('Scientific choices', 'full'),
    '--execution': ('Execution', 'full'),
    '--expand': ('Scientific choices', 'short'),
    '--export': ('Outputs and plots', 'short'),
    '--export-all': ('Outputs and plots', 'full'),
    '--expr': ('Scientific choices', 'full'),
    '--ext': ('Scientific choices', 'full'),
    '--extxyz-precision': ('Outputs and plots', 'full'),
    '--ffield': ('Input and file selection', 'short'),
    '--field': ('Scientific choices', 'short'),
    '--field-direction': ('Scientific choices', 'full'),
    '--field-kind': ('Scientific choices', 'full'),
    '--field-method': ('Scientific choices', 'full'),
    '--fields': ('Scientific choices', 'full'),
    '--field-step': ('Scientific choices', 'full'),
    '--figure-dpi': ('Outputs and plots', 'full'),
    '--file': ('Input and file selection', 'short'),
    '--fill-missing-with-template': ('Scientific choices', 'full'),
    '--fill-value': ('Scientific choices', 'full'),
    '--final-polarization': ('Scientific choices', 'full'),
    '--fit-nls-amplitude': ('Scientific choices', 'full'),
    '--fixed': ('Scientific choices', 'full'),
    '--flip-sign': ('Scientific choices', 'full'),
    '--flip-sign-for-eos': ('Scientific choices', 'full'),
    '--folder': ('Input and file selection', 'short'),
    '--force': ('Storage and cache', 'full'),
    '--formal-charge': ('Scientific choices', 'short'),
    '--format': ('Outputs and plots', 'full'),
    '--fort13': ('Input and file selection', 'full'),
    '--fort57': ('Input and file selection', 'full'),
    '--fort7': ('Input and file selection', 'short'),
    '--fort73': ('Input and file selection', 'full'),
    '--fort74': ('Input and file selection', 'full'),
    '--fort76': ('Input and file selection', 'full'),
    '--fort78': ('Input and file selection', 'full'),
    '--fort79': ('Input and file selection', 'full'),
    '--fort83': ('Input and file selection', 'full'),
    '--fort99': ('Input and file selection', 'full'),
    '--fps': ('Outputs and plots', 'full'),
    '--frame': ('Scientific choices', 'short'),
    '--frame-cache-max-gb': ('Storage and cache', 'full'),
    '--frame-count': ('Scientific choices', 'full'),
    '--frames': ('Scientific choices', 'short'),
    '--frame-source': ('Scientific choices', 'full'),
    '--frequency-unit': ('Scientific choices', 'full'),
    '--gap-deg': ('Scientific choices', 'full'),
    '--gas-constant': ('Scientific choices', 'full'),
    '--gen-plots': ('Outputs and plots', 'full'),
    '--gen-yaml': ('Outputs and plots', 'full'),
    '--geo': ('Input and file selection', 'short'),
    '--geo-file': ('Input and file selection', 'full'),
    '--global-objective-scale': ('Scientific choices', 'full'),
    '--global-scaling': ('Outputs and plots', 'full'),
    '--global-y-axis': ('Outputs and plots', 'full'),
    '--grid': ('Outputs and plots', 'full'),
    '--group-column': ('Scientific choices', 'full'),
    '--help': ('Diagnostics and compatibility', 'full'),
    '--heatmap-component': ('Scientific choices', 'full'),
    '--heatmap-plane': ('Scientific choices', 'full'),
    '--heatmaps': ('Outputs and plots', 'full'),
    '--help-all': ('Diagnostics and compatibility', 'full'),
    '--hf-base': ('Input and file selection', 'full'),
    '--hf-output-name': ('Outputs and plots', 'full'),
    '--how': ('Scientific choices', 'full'),
    '--hybridizations': ('Scientific choices', 'full'),
    '--hysteresis': ('Scientific choices', 'full'),
    '--iden': ('Scientific choices', 'full'),
    '--identifier': ('Scientific choices', 'full'),
    '--include-electric-field': ('Outputs and plots', 'full'),
    '--include-geo-descriptor': ('Outputs and plots', 'full'),
    '--include-noncarbon': ('Scientific choices', 'full'),
    '--include-self': ('Scientific choices', 'full'),
    '--init': ('Input and file selection', 'full'),
    '--initial': ('Scientific choices', 'full'),
    '--initial-polarization': ('Scientific choices', 'full'),
    '--input': ('Input and file selection', 'short'),
    '--input-cache': ('Storage and cache', 'full'),
    '--input-mode': ('Input and file selection', 'full'),
    '--insert': ('Scientific choices', 'short'),
    '--interpret': ('Scientific choices', 'full'),
    '--isomer-dir': ('Input and file selection', 'full'),
    '--iteration-step': ('Scientific choices', 'short'),
    '--job-config': ('Input and file selection', 'full'),
    '--job-dir': ('Input and file selection', 'full'),
    '--keep-atoms-in-dest': ('Scientific choices', 'full'),
    '--keep-coord-original': ('Scientific choices', 'full'),
    '--keep-duplicates': ('Scientific choices', 'full'),
    '--key': ('Scientific choices', 'short'),
    '--kymograph-time-axis': ('Outputs and plots', 'full'),
    '--kymograph-values': ('Outputs and plots', 'full'),
    '--label': ('Scientific choices', 'full'),
    '--labels': ('Outputs and plots', 'full'),
    '--last': ('Scientific choices', 'full'),
    '--local-charge-treatment': ('Scientific choices', 'full'),
    '--local-grouping': ('Scientific choices', 'short'),
    '--local-volume-method': ('Scientific choices', 'full'),
    '--log': ('Diagnostics and compatibility', 'full'),
    '--log-file': ('Input and file selection', 'full'),
    '--log-in-terminal': ('Diagnostics and compatibility', 'full'),
    '--loss': ('Scientific choices', 'full'),
    '--make-yaml': ('Outputs and plots', 'short'),
    '--manage': ('Input and file selection', 'full'),
    '--marker-size': ('Outputs and plots', 'full'),
    '--mascen': ('Scientific choices', 'full'),
    '--mat-id': ('Input and file selection', 'short'),
    '--max': ('Scientific choices', 'full'),
    '--max-alignment-candidates': ('Scientific choices', 'full'),
    '--maxattempt': ('Scientific choices', 'full'),
    '--max-condition-number': ('Scientific choices', 'full'),
    '--max-diag-frames': ('Diagnostics and compatibility', 'full'),
    '--max-frequency': ('Scientific choices', 'full'),
    '--max-lag': ('Scientific choices', 'full'),
    '--max-magnitude': ('Scientific choices', 'full'),
    '--max-materials': ('Scientific choices', 'full'),
    '--max-reference-strain': ('Scientific choices', 'full'),
    '--max-representatives': ('Scientific choices', 'full'),
    '--median': ('Scientific choices', 'full'),
    '--min': ('Scientific choices', 'full'),
    '--min-bo': ('Scientific choices', 'full'),
    '--mindist': ('Scientific choices', 'full'),
    '--min-freq': ('Scientific choices', 'full'),
    '--minimum-atoms': ('Scientific choices', 'full'),
    '--min-points': ('Scientific choices', 'full'),
    '--min-run': ('Scientific choices', 'full'),
    '--mode': ('Scientific choices', 'short'),
    '--molecules': ('Scientific choices', 'short'),
    '--molfra': ('Input and file selection', 'full'),
    '--ncopy': ('Scientific choices', 'short'),
    '--neighbor': ('Scientific choices', 'full'),
    '--neighbor-cutoff': ('Scientific choices', 'full'),
    '--no-isomer-dirs': ('Outputs and plots', 'full'),
    '--normalization': ('Scientific choices', 'full'),
    '--no-shift-min-to-zero': ('Scientific choices', 'full'),
    '--no-skip-completed': ('Execution', 'full'),
    '--no-skip-queued': ('Execution', 'full'),
    '--nucleation-density': ('Scientific choices', 'full'),
    '--number': ('Scientific choices', 'full'),
    '--num-cycles': ('Scientific choices', 'full'),
    '--older-than': ('Storage and cache', 'full'),
    '--ordered-2body': ('Scientific choices', 'full'),
    '--origin': ('Scientific choices', 'full'),
    '--orthogonalize-reference': ('Scientific choices', 'full'),
    '--orthogonalize': ('Scientific choices', 'full'),
    '--outdir': ('Outputs and plots', 'short'),
    '--output': ('Outputs and plots', 'short'),
    '--output-dir': ('Outputs and plots', 'short'),
    '--output-profile': ('Storage and cache', 'full'),
    '--out-yaml': ('Outputs and plots', 'full'),
    '--overwrite': ('Storage and cache', 'full'),
    '--oxygen-element': ('Scientific choices', 'full'),
    '--parallel-workers': ('Execution', 'full'),
    '--parameter': ('Scientific choices', 'full'),
    '--params': ('Input and file selection', 'full'),
    '--per-atom': ('Scientific choices', 'full'),
    '--per-atom-type': ('Scientific choices', 'full'),
    '--period': ('Scientific choices', 'full'),
    '--periodic': ('Scientific choices', 'short'),
    '--persist': ('Outputs and plots', 'full'),
    '--phase': ('Scientific choices', 'full'),
    '--plane': ('Scientific choices', 'short'),
    '--plot': ('Outputs and plots', 'short'),
    '--plot-2d': ('Outputs and plots', 'short'),
    '--plot-3d': ('Outputs and plots', 'full'),
    '--plot-bins': ('Outputs and plots', 'full'),
    '--plot-component': ('Outputs and plots', 'full'),
    '--plot-every': ('Outputs and plots', 'full'),
    '--plot-field-component': ('Outputs and plots', 'full'),
    '--plot-field-units': ('Outputs and plots', 'full'),
    '--plot-frames': ('Outputs and plots', 'full'),
    '--plot-kymograph': ('Outputs and plots', 'short'),
    '--plot-plane': ('Outputs and plots', 'full'),
    '--plot-quantity': ('Outputs and plots', 'full'),
    '--plot-real-values': ('Outputs and plots', 'full'),
    '--plot-target': ('Outputs and plots', 'full'),
    '--plot-value': ('Outputs and plots', 'full'),
    '--points-per-cycle': ('Scientific choices', 'full'),
    '--polarity-columns': ('Scientific choices', 'full'),
    '--polarity-tolerance': ('Scientific choices', 'full'),
    '--potential-reference-mode': ('Scientific choices', 'full'),
    '--potential-reference-position': ('Scientific choices', 'full'),
    '--precision': ('Outputs and plots', 'full'),
    '--present': ('Outputs and plots', 'full'),
    '--probe-elements': ('Scientific choices', 'full'),
    '--profile-axis': ('Scientific choices', 'short'),
    '--progress': ('Diagnostics and compatibility', 'full'),
    '--progress-every': ('Diagnostics and compatibility', 'full'),
    '--projection': ('Scientific choices', 'short'),
    '--projection-bins': ('Scientific choices', 'short'),
    '--projection-plane': ('Scientific choices', 'short'),
    '--project-root': ('Storage and cache', 'full'),
    '--prop': ('Scientific choices', 'full'),
    '--property': ('Scientific choices', 'short'),
    '--proton': ('Scientific choices', 'full'),
    '--proton-cutoff': ('Scientific choices', 'full'),
    '--quantities': ('Scientific choices', 'full'),
    '--radius-metrics': ('Scientific choices', 'full'),
    '--randomseed': ('Scientific choices', 'full'),
    '--raw-root': ('Input and file selection', 'full'),
    '--r-co': ('Scientific choices', 'full'),
    '--r-csi': ('Scientific choices', 'full'),
    '--reference': ('Scientific choices', 'short'),
    '--reference-composition': ('Scientific choices', 'full'),
    '--reference-frame': ('Scientific choices', 'short'),
    '--references': ('Input and file selection', 'full'),
    '--reference-species': ('Scientific choices', 'full'),
    '--regex': ('Scientific choices', 'full'),
    '--replace-existing': ('Storage and cache', 'full'),
    '--replicate': ('Scientific choices', 'full'),
    '--replication': ('Scientific choices', 'short'),
    '--report': ('Outputs and plots', 'short'),
    '--report-format': ('Outputs and plots', 'full'),
    '--report-most-sensitive': ('Scientific choices', 'full'),
    '--require-all-complete': ('Scientific choices', 'full'),
    '--rerun-failed': ('Execution', 'full'),
    '--rest': ('Scientific choices', 'full'),
    '--restraint-index': ('Scientific choices', 'full'),
    '--rkf': ('Input and file selection', 'full'),
    '--r-max': ('Scientific choices', 'full'),
    '--root': ('Input and file selection', 'short'),
    '--roots': ('Input and file selection', 'full'),
    '--rows': ('Outputs and plots', 'full'),
    '--r-probe': ('Scientific choices', 'full'),
    '--run': ('Scientific choices', 'full'),
    '--run-dir': ('Input and file selection', 'short'),
    '--run-geometry-generator': ('Scientific choices', 'full'),
    '--run-id': ('Storage and cache', 'full'),
    '--same-general-order': ('Scientific choices', 'full'),
    '--save': ('Outputs and plots', 'full'),
    '--scale-by': ('Scientific choices', 'full'),
    '--scatter': ('Outputs and plots', 'full'),
    '--scope': ('Scientific choices', 'short'),
    '--section': ('Scientific choices', 'full'),
    '--seed': ('Scientific choices', 'full'),
    '--sheet': ('Outputs and plots', 'full'),
    '--show': ('Outputs and plots', 'full'),
    '--silicon-element': ('Scientific choices', 'full'),
    '--similarity': ('Scientific choices', 'full'),
    '--simulation': ('Input and file selection', 'full'),
    '--size': ('Scientific choices', 'full'),
    '--skip-detailed-csv': ('Outputs and plots', 'full'),
    '--skip-negative-elastic-data': ('Scientific choices', 'full'),
    '--skip-not-orthogonal': ('Scientific choices', 'full'),
    '--skip-plots': ('Outputs and plots', 'full'),
    '--slice-range': ('Scientific choices', 'full'),
    '--slope': ('Scientific choices', 'full'),
    '--smooth': ('Scientific choices', 'full'),
    '--soap': ('Scientific choices', 'full'),
    '--soap-l-max': ('Scientific choices', 'full'),
    '--soap-n-max': ('Scientific choices', 'full'),
    '--soap-r-cut': ('Scientific choices', 'full'),
    '--soap-ref-path': ('Scientific choices', 'full'),
    '--soap-zeta': ('Scientific choices', 'full'),
    '--sort': ('Scientific choices', 'full'),
    '--source': ('Input and file selection', 'short'),
    '--src': ('Scientific choices', 'full'),
    '--stage': ('Scientific choices', 'full'),
    '--start-iter': ('Scientific choices', 'full'),
    '--starts': ('Scientific choices', 'full'),
    '--step-angle': ('Scientific choices', 'full'),
    '--step-size': ('Scientific choices', 'full'),
    '--stream': ('Execution', 'full'),
    '--strict-actions': ('Scientific choices', 'full'),
    '--strict-tract': ('Scientific choices', 'full'),
    '--structure-dir': ('Input and file selection', 'full'),
    '--submit': ('Execution', 'full'),
    '--summary': ('Input and file selection', 'full'),
    '--surface': ('Scientific choices', 'short'),
    '--sweep': ('Scientific choices', 'full'),
    '--tail-fraction': ('Scientific choices', 'full'),
    '--target': ('Scientific choices', 'short'),
    '--target-atom-ids': ('Scientific choices', 'full'),
    '--target-elements': ('Scientific choices', 'full'),
    '--temperature': ('Scientific choices', 'full'),
    '--template-closest-atom': ('Scientific choices', 'full'),
    '--template-map': ('Input and file selection', 'full'),
    '--template-radius-metrics': ('Scientific choices', 'full'),
    '--template-similarity': ('Scientific choices', 'full'),
    '--t-end': ('Scientific choices', 'full'),
    '--term': ('Scientific choices', 'short'),
    '--thickness': ('Scientific choices', 'full'),
    '--threshold': ('Scientific choices', 'short'),
    '--time-column': ('Scientific choices', 'full'),
    '--timestep-fs': ('Scientific choices', 'full'),
    '--time-unit': ('Scientific choices', 'full'),
    '--timing': ('Diagnostics and compatibility', 'full'),
    '--title': ('Outputs and plots', 'full'),
    '--top': ('Scientific choices', 'full'),
    '--top-bottom-count': ('Scientific choices', 'full'),
    '--top-n': ('Scientific choices', 'full'),
    '--torsion': ('Scientific choices', 'full'),
    '--trainset': ('Input and file selection', 'full'),
    '--trainset-file': ('Input and file selection', 'full'),
    '--trajectory': ('Input and file selection', 'short'),
    '--type': ('Scientific choices', 'short'),
    '--undirected': ('Scientific choices', 'full'),
    '--units': ('Scientific choices', 'full'),
    '--unwrap': ('Scientific choices', 'full'),
    '--V': ('Scientific choices', 'full'),
    '--vacuum': ('Scientific choices', 'short'),
    '--valences': ('Scientific choices', 'full'),
    '--value': ('Scientific choices', 'full'),
    '--value-column': ('Scientific choices', 'full'),
    '--vels': ('Input and file selection', 'full'),
    '--verbose': ('Diagnostics and compatibility', 'full'),
    '--view-azimuth': ('Outputs and plots', 'full'),
    '--view-elevation': ('Outputs and plots', 'full'),
    '--vline': ('Outputs and plots', 'full'),
    '--vmax': ('Outputs and plots', 'full'),
    '--vmin': ('Outputs and plots', 'full'),
    '--volume': ('Scientific choices', 'full'),
    '--volume-method': ('Scientific choices', 'short'),
    '--volume-unit': ('Scientific choices', 'full'),
    '--wall-velocity': ('Scientific choices', 'full'),
    '--weight': ('Scientific choices', 'full'),
    '--wide': ('Outputs and plots', 'full'),
    '--width': ('Outputs and plots', 'full'),
    '--window': ('Scientific choices', 'full'),
    '--workers': ('Execution', 'full'),
    '--workspace-root': ('Storage and cache', 'full'),
    '--wrapped': ('Scientific choices', 'full'),
    '--write-centers': ('Outputs and plots', 'full'),
    '--write-detailed-charges': ('Outputs and plots', 'full'),
    '--write-displacements': ('Outputs and plots', 'full'),
    '--write-example-config': ('Outputs and plots', 'full'),
    '--write-extxyz': ('Outputs and plots', 'short'),
    '--write-isomer-dirs': ('Outputs and plots', 'full'),
    '--x': ('Scientific choices', 'full'),
    '--xaxis': ('Outputs and plots', 'full'),
    '--x-axis': ('Outputs and plots', 'full'),
    '--xlabel': ('Outputs and plots', 'full'),
    '--xmolout': ('Input and file selection', 'short'),
    '--y': ('Scientific choices', 'full'),
    '--y1': ('Scientific choices', 'full'),
    '--y2': ('Scientific choices', 'full'),
    '--yaml': ('Input and file selection', 'short'),
    '--yaxis': ('Outputs and plots', 'short'),
    '--ylabel': ('Outputs and plots', 'full'),
    '--ylabel1': ('Outputs and plots', 'full'),
    '--ylabel2': ('Outputs and plots', 'full'),
    '--y-scale': ('Outputs and plots', 'full'),
    '--z': ('Scientific choices', 'full'),
    '--z-bins': ('Scientific choices', 'short'),
    '--zero-tolerance': ('Scientific choices', 'full'),
}
